[package]
name = "dankly"
version = "0.0.1"
authors = ["dingo-actual <ryan@beta-reduce.net>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
rand_distr = "0.2.2"
ndarray = "0.13.1"
ndarray-rand = "0.11.0"
num-traits = "0.2.11"